# Data Viz Assignment

### Importing packages

In [13]:
# importing required packages
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tabulate
import pycountry as pc
import pycountry_convert as pcc
import prophet as prt
import statsmodels as sm
import datetime as dt
import streamlit as st
import plotly.express as px

### Loading datasets

In [14]:
# loading temperature anomaly dataset
temp_df = pd.read_csv("../data/annual-temperature-anomalies.csv")

# loading co2 emissions dataset
co2_df = pd.read_csv("../data/owid-co2-data.csv")

### Merging data

In [15]:
# merging temperature and co2 datasets
# merged on year and country
df = pd.merge(temp_df, co2_df,
              left_on = ["Entity", "Year"],
              right_on = ["country", "year"],
              how = "inner")

### Dataset overview

Initial exploration of the datasets to assess dataset structure and contents.

In [16]:
# creating a function to assess data structure and contents
# using a report like structure for readability
def info_stats(df):

    # creating title
    print("\n" + "="*60)
    print("DATASET OVERVIEW")  
    print("="*60)

    # getting column names
    print("\n Columns:")
    print(list(df.columns.values)) 
    
    # getting row and columns totals
    print("\n Shape (rows, columns):")
    print(df.shape) 
    
    # viewing top 5 rows
    print("\n First 5 rows:")
    print(df.head()) 
    
    # viewing last 5 rows
    print("\n Last 5 rows:")
    print(df.tail()) 
    
    # collecting data info
    print("\n Data Info:")
    df.info()
    
    # getting summary statistics
    print("\n Summary Statistics:")
    summary_statistics = df.describe().round(2)
    table = tabulate.tabulate(summary_statistics, headers='keys', tablefmt='pretty')
    print(table)
    
    # adding a seperator for readabilty
    print("\n" + "="*60 + "\n")

In [17]:
# applying the info_stats function created in the previous code block
info_stats(df)

============================================================
DATASET OVERVIEW
============================================================

 Columns:
['Entity', 'Code', 'Year', 'Temperature anomaly', 'country', 'year', 'iso_code', 'population', 'gdp', 'cement_co2', 'cement_co2_per_capita', 'co2', 'co2_growth_abs', 'co2_growth_prct', 'co2_including_luc', 'co2_including_luc_growth_abs', 'co2_including_luc_growth_prct', 'co2_including_luc_per_capita', 'co2_including_luc_per_gdp', 'co2_including_luc_per_unit_energy', 'co2_per_capita', 'co2_per_gdp', 'co2_per_unit_energy', 'coal_co2', 'coal_co2_per_capita', 'consumption_co2', 'consumption_co2_per_capita', 'consumption_co2_per_gdp', 'cumulative_cement_co2', 'cumulative_co2', 'cumulative_co2_including_luc', 'cumulative_coal_co2', 'cumulative_flaring_co2', 'cumulative_gas_co2', 'cumulative_luc_co2', 'cumulative_oil_co2', 'cumulative_other_co2', 'energy_per_capita', 'energy_per_gdp', 'flaring_co2', 'flaring_co2_per_capita', 'gas_co2', 'gas_co2_per_capita', 'ghg_excluding_lucf_per_capita', 'ghg_per_capita', 'land_use_change_co2', 'land_use_change_co2_per_capita', 'methane', 'methane_per_capita', 'nitrous_oxide', 'nitrous_oxide_per_capita', 'oil_co2', 'oil_co2_per_capita', 'other_co2_per_capita', 'other_industry_co2', 'primary_energy_consumption', 'share_global_cement_co2', 'share_global_co2', 'share_global_co2_including_luc', 'share_global_coal_co2', 'share_global_cumulative_cement_co2', 'share_global_cumulative_co2', 'share_global_cumulative_co2_including_luc', 'share_global_cumulative_coal_co2', 'share_global_cumulative_flaring_co2', 'share_global_cumulative_gas_co2', 'share_global_cumulative_luc_co2', 'share_global_cumulative_oil_co2', 'share_global_cumulative_other_co2', 'share_global_flaring_co2', 'share_global_gas_co2', 'share_global_luc_co2', 'share_global_oil_co2', 'share_global_other_co2', 'share_of_temperature_change_from_ghg', 'temperature_change_from_ch4', 'temperature_change_from_co2', 'temperature_change_from_ghg', 'temperature_change_from_n2o', 'total_ghg', 'total_ghg_excluding_lucf', 'trade_co2', 'trade_co2_share']

 Shape (rows, columns):
(15895, 83)

 First 5 rows:
        Entity Code  Year  Temperature anomaly      country  year iso_code  \
0  Afghanistan  AFG  1940            -1.202316  Afghanistan  1940      AFG
1  Afghanistan  AFG  1941             0.794745  Afghanistan  1941      AFG
2  Afghanistan  AFG  1942             0.355437  Afghanistan  1942      AFG
3  Afghanistan  AFG  1943            -1.005242  Afghanistan  1943      AFG
4  Afghanistan  AFG  1944            -0.386346  Afghanistan  1944      AFG

   population  gdp  cement_co2  ...  share_global_other_co2  \
0   6468510.0  NaN         0.0  ...                     NaN
1   6528377.0  NaN         0.0  ...                     NaN
2   6608815.0  NaN         0.0  ...                     NaN
3   6710138.0  NaN         0.0  ...                     NaN
4   6813016.0  NaN         0.0  ...                     NaN

   share_of_temperature_change_from_ghg  temperature_change_from_ch4  \
0                              0.131898                     0.000155
1                              0.131601                     0.000159
2                              0.131366                     0.000163
3                              0.131178                     0.000167
4                              0.131037                     0.000171

   temperature_change_from_co2  temperature_change_from_ghg  \
0                     0.000271                     0.000447
1                     0.000275                     0.000455
2                     0.000279                     0.000464
3                     0.000283                     0.000472
4                     0.000286                     0.000481

   temperature_change_from_n2o  total_ghg  total_ghg_excluding_lucf  \
0                     0.000021  16.603607                  1.185990
1                     0.000022  16.855204                  1.202408
2                     0.000022  17.041975                  1.219419
3                     0.000023  17.262272                  1.236890
4                     0.000024  17.617689                  1.254759

   trade_co2  trade_co2_share
0        NaN              NaN
1        NaN              NaN
2        NaN              NaN
3        NaN              NaN
4        NaN              NaN

[5 rows x 83 columns]

 Last 5 rows:
         Entity Code  Year  Temperature anomaly   country  year iso_code  \
15890  Zimbabwe  ZWE  2020             0.229293  Zimbabwe  2020      ZWE
15891  Zimbabwe  ZWE  2021             0.016838  Zimbabwe  2021      ZWE
15892  Zimbabwe  ZWE  2022             0.035659  Zimbabwe  2022      ZWE
15893  Zimbabwe  ZWE  2023             0.792851  Zimbabwe  2023      ZWE
15894  Zimbabwe  ZWE  2024             1.364956  Zimbabwe  2024      ZWE

       population           gdp  cement_co2  ...  share_global_other_co2  \
15890  15526887.0  2.317871e+10    0.495991  ...                     NaN
15891  15797220.0  2.514009e+10    0.542490  ...                     NaN
15892  16069061.0  2.590159e+10    0.387493  ...                     NaN
15893  16340829.0           NaN    0.387493  ...                     NaN
15894  16634366.0           NaN    0.387493  ...                     NaN

       share_of_temperature_change_from_ghg  temperature_change_from_ch4  \
15890                              0.105596                     0.000526
15891                              0.104508                     0.000527
15892                              0.103672                     0.000531
15893                              0.102958                     0.000536
15894                              0.102267                     0.000542

       temperature_change_from_co2  temperature_change_from_ghg  \
15890                     0.000972                     0.001669
15891                     0.000977                     0.001677
15892                     0.000982                     0.001689
15893                     0.000988                     0.001703
15894                     0.000994                     0.001716

       temperature_change_from_n2o  total_ghg  total_ghg_excluding_lucf  \
15890                     0.000171  24.145832                 14.463331
15891                     0.000173  27.906528                 16.408270
15892                     0.000176  29.916828                 18.830246
15893                     0.000178  31.028685                 20.318186
15894                     0.000180  31.066437                 20.773445

       trade_co2  trade_co2_share
15890   1.991086        23.449816
15891   2.136505        20.899456
15892   1.380109        11.282917
15893   1.876236        13.956668
15894        NaN              NaN

[5 rows x 83 columns]

 Data Info:
<class 'pandas.DataFrame'>
RangeIndex: 15895 entries, 0 to 15894
Data columns (total 83 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Entity                                     15895 non-null  str
 1   Code                                       15895 non-null  str
 2   Year                                       15895 non-null  int64
 3   Temperature anomaly                        15895 non-null  float64
 4   country                                    15895 non-null  str
 5   year                                       15895 non-null  int64
 6   iso_code                                   15725 non-null  str
 7   population                                 15812 non-null  float64
 8   gdp                                        11513 non-null  float64
 9   cement_co2                                 14223 non-null  float64
 10  cement_co2_per_capita                      14204 non-null  float64
 11  co2                                        14515 non-null  float64
 12  co2_growth_abs                             14413 non-null  float64
 13  co2_growth_prct                            14391 non-null  float64
 14  co2_including_luc                          14030 non-null  float64
 15  co2_including_luc_growth_abs               13938 non-null  float64
 16  co2_including_luc_growth_prct              13938 non-null  float64
 17  co2_including_luc_per_capita               14020 non-null  float64
 18  co2_including_luc_per_gdp                  11207 non-null  float64
 19  co2_including_luc_per_unit_energy          8552 non-null   float64
 20  co2_per_capita                             14505 non-null  float64
 21  co2_per_gdp                                11280 non-null  float64
 22  co2_per_unit_energy                        8847 non-null   float64
 23  coal_co2                                   10855 non-null  float64
 24  coal_co2_per_capita                        10845 non-null  float64
 25  consumption_co2                            3997 non-null   float64
 26  consumption_co2_per_capita                 3997 non-null   float64
 27  consumption_co2_per_gdp                    3821 non-null   float64
 28  cumulative_cement_co2                      14223 non-null  float64
 29  cumulative_co2                             14515 non-null  float64
 30  cumulative_co2_including_luc               14030 non-null  float64
 31  cumulative_coal_co2                        10855 non-null  float64
 32  cumulative_flaring_co2                     8820 non-null   float64
 33  cumulative_gas_co2                         8349 non-null   float64
 34  cumulative_luc_co2                         15215 non-null  float64
 35  cumulative_oil_co2                         14288 non-null  float64
 36  cumulative_other_co2                       1670 non-null   float64
 37  energy_per_capita                          8865 non-null   float64
 38  energy_per_gdp                             7499 non-null   float64
 39  flaring_co2                                8820 non-null   float64
 40  flaring_co2_per_capita                     8820 non-null   float64
 41  gas_co2                                    8349 non-null   float64
 42  gas_co2_per_capita                         8339 non-null   float64
 43  ghg_excluding_lucf_per_capita              15187 non-null  float64
 44  ghg_per_capita                             15272 non-null  float64
 45  land_use_change_co2                        15215 non-null  float64
 46  land_use_change_co2_per_capita             15196 non-null  float64
 47  methane                                    15300 non-null  float64
 48  methane_per_capita                         15272 non-null  float64
 49  nitrous_oxide                              15385 non-null  float64
 50  nitrous_oxide_per_capita                   15348 non-null  float64
 51  oil_co2                                    14288 non-null  float64
 52  oil_co2_per_capita                         14278 non-null  float64
 53  other_co2_per_capita                       1670 non-null   float64
 54  other_industry_co2                         1670 non-null   float64
 55  primary_energy_consumption                 8865 non-null   float64
 56  share_global_cement_co2                    14223 non-null  float64
 57  share_global_co2                           14515 non-null  float64
 58  share_global_co2_including_luc             14030 non-null  float64
 59  share_global_coal_co2                      10855 non-null  float64
 60  share_global_cumulative_cement_co2         14223 non-null  float64
 61  share_global_cumulative_co2                14515 non-null  float64
 62  share_global_cumulative_co2_including_luc  14030 non-null  float64
 63  share_global_cumulative_coal_co2           10855 non-null  float64
 64  share_global_cumulative_flaring_co2        8567 non-null   float64
 65  share_global_cumulative_gas_co2            8349 non-null   float64
 66  share_global_cumulative_luc_co2            15215 non-null  float64
 67  share_global_cumulative_oil_co2            14288 non-null  float64
 68  share_global_cumulative_other_co2          1540 non-null   float64
 69  share_global_flaring_co2                   8567 non-null   float64
 70  share_global_gas_co2                       8349 non-null   float64
 71  share_global_luc_co2                       15215 non-null  float64
 72  share_global_oil_co2                       14288 non-null  float64
 73  share_global_other_co2                     1540 non-null   float64
 74  share_of_temperature_change_from_ghg       15895 non-null  float64
 75  temperature_change_from_ch4                15385 non-null  float64
 76  temperature_change_from_co2                15895 non-null  float64
 77  temperature_change_from_ghg                15895 non-null  float64
 78  temperature_change_from_n2o                15385 non-null  float64
 79  total_ghg                                  15300 non-null  float64
 80  total_ghg_excluding_lucf                   15215 non-null  float64
 81  trade_co2                                  3996 non-null   float64
 82  trade_co2_share                            3996 non-null   float64
dtypes: float64(77), int64(2), str(4)
memory usage: 10.4 MB

 Summary Statistics:
+-------+---------+---------------------+---------+--------------+-------------------+------------+-----------------------+----------+----------------+-----------------+-------------------+------------------------------+-------------------------------+------------------------------+---------------------------+-----------------------------------+----------------+-------------+---------------------+----------+---------------------+-----------------+----------------------------+-------------------------+-----------------------+----------------+------------------------------+---------------------+------------------------+--------------------+--------------------+--------------------+----------------------+-------------------+----------------+-------------+------------------------+---------+--------------------+-------------------------------+----------------+---------------------+--------------------------------+---------+--------------------+---------------+--------------------------+---------+--------------------+----------------------+--------------------+----------------------------+-------------------------+------------------+--------------------------------+-----------------------+------------------------------------+-----------------------------+-------------------------------------------+----------------------------------+-------------------------------------+---------------------------------+---------------------------------+---------------------------------+-----------------------------------+--------------------------+----------------------+----------------------+----------------------+------------------------+--------------------------------------+-----------------------------+-----------------------------+-----------------------------+-----------------------------+-----------+--------------------------+-----------+-----------------+
|       |  Year   | Temperature anomaly |  year   |  population  |        gdp        | cement_co2 | cement_co2_per_capita |   co2    | co2_growth_abs | co2_growth_prct | co2_including_luc | co2_including_luc_growth_abs | co2_including_luc_growth_prct | co2_including_luc_per_capita | co2_including_luc_per_gdp | co2_including_luc_per_unit_energy | co2_per_capita | co2_per_gdp | co2_per_unit_energy | coal_co2 | coal_co2_per_capita | consumption_co2 | consumption_co2_per_capita | consumption_co2_per_gdp | cumulative_cement_co2 | cumulative_co2 | cumulative_co2_including_luc | cumulative_coal_co2 | cumulative_flaring_co2 | cumulative_gas_co2 | cumulative_luc_co2 | cumulative_oil_co2 | cumulative_other_co2 | energy_per_capita | energy_per_gdp | flaring_co2 | flaring_co2_per_capita | gas_co2 | gas_co2_per_capita | ghg_excluding_lucf_per_capita | ghg_per_capita | land_use_change_co2 | land_use_change_co2_per_capita | methane | methane_per_capita | nitrous_oxide | nitrous_oxide_per_capita | oil_co2 | oil_co2_per_capita | other_co2_per_capita | other_industry_co2 | primary_energy_consumption | share_global_cement_co2 | share_global_co2 | share_global_co2_including_luc | share_global_coal_co2 | share_global_cumulative_cement_co2 | share_global_cumulative_co2 | share_global_cumulative_co2_including_luc | share_global_cumulative_coal_co2 | share_global_cumulative_flaring_co2 | share_global_cumulative_gas_co2 | share_global_cumulative_luc_co2 | share_global_cumulative_oil_co2 | share_global_cumulative_other_co2 | share_global_flaring_co2 | share_global_gas_co2 | share_global_luc_co2 | share_global_oil_co2 | share_global_other_co2 | share_of_temperature_change_from_ghg | temperature_change_from_ch4 | temperature_change_from_co2 | temperature_change_from_ghg | temperature_change_from_n2o | total_ghg | total_ghg_excluding_lucf | trade_co2 | trade_co2_share |
+-------+---------+---------------------+---------+--------------+-------------------+------------+-----------------------+----------+----------------+-----------------+-------------------+------------------------------+-------------------------------+------------------------------+---------------------------+-----------------------------------+----------------+-------------+---------------------+----------+---------------------+-----------------+----------------------------+-------------------------+-----------------------+----------------+------------------------------+---------------------+------------------------+--------------------+--------------------+--------------------+----------------------+-------------------+----------------+-------------+------------------------+---------+--------------------+-------------------------------+----------------+---------------------+--------------------------------+---------+--------------------+---------------+--------------------------+---------+--------------------+----------------------+--------------------+----------------------------+-------------------------+------------------+--------------------------------+-----------------------+------------------------------------+-----------------------------+-------------------------------------------+----------------------------------+-------------------------------------+---------------------------------+---------------------------------+---------------------------------+-----------------------------------+--------------------------+----------------------+----------------------+----------------------+------------------------+--------------------------------------+-----------------------------+-----------------------------+-----------------------------+-----------------------------+-----------+--------------------------+-----------+-----------------+

### Data cleaning and preprocessing

Cleaning the data by removing unwanted columns and rows. This includes rows that contain NA values in key statistical columns needed for the analysis.

In [18]:
# defining column list for filtering
columns = ["Year", "country", "iso_code", "population", "gdp", "energy_per_capita", "Temperature anomaly",
           "co2", "co2_per_capita", "co2_including_luc",
           "land_use_change_co2", "coal_co2", "oil_co2", "gas_co2", "share_global_co2", "temperature_change_from_co2"]

In [19]:
# filtering dataframe for only selected columns
df = df[columns]
df.shape

(15895, 16)

In [20]:
world_df = df[df['country'] == "World"]
world_df

,Year,country,iso_code,population,gdp,energy_per_capita,Temperature anomaly,co2,co2_per_capita,co2_including_luc,land_use_change_co2,coal_co2,oil_co2,gas_co2,share_global_co2,temperature_change_from_co2
15555,1940,World,NaN,2.291980e+09,7.646890e+12,NaN,-0.686135,4884.661621,2.131198,10628.067383,5743.405762,3795.503174,900.980530,153.519745,100.0,0.247305
15556,1941,World,NaN,2.312099e+09,NaN,NaN,-0.641774,4999.090332,2.162144,10890.240234,5891.149902,3885.962891,912.336914,153.463226,100.0,0.252204
15557,1942,World,NaN,2.331135e+09,NaN,NaN,-0.732430,4982.523438,2.137381,10887.828125,5905.305176,3910.556152,863.507507,166.048950,100.0,0.257101
15558,1943,World,NaN,2.349015e+09,NaN,NaN,-0.726379,5075.272461,2.160596,10969.573242,5894.301270,3926.686035,926.590759,182.899902,100.0,0.262035
15559,1944,World,NaN,2.366919e+09,NaN,NaN,-0.534997,5162.485840,2.181100,10988.550781,5826.065430,3869.107178,1068.786133,197.600830,100.0,0.266977
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15635,2020,World,NaN,7.887001e+09,1.185900e+14,20032.187500,0.432163,35158.230469,4.457744,39674.769531,4516.539551,14267.035156,10932.341797,7520.819824,100.0,1.141716
15636,2021,World,NaN,7.954448e+09,1.260048e+14,20874.294922,0.273691,36866.863281,4.634748,41523.964844,4657.103027,14969.249023,11513.166016,7878.698242,100.0,1.160024
15637,2022,World,NaN,8.021407e+09,1.301126e+14,21076.292969,0.300865,37527.773438,4.678452,42313.164062,4785.391602,15449.176758,11914.912109,7758.745605,100.0,1.178648
15638,2023,World,NaN,8.091735e+09,NaN,21285.767578,0.600733,38094.039062,4.707772,42839.593750,4745.551270,15636.373047,12278.241211,7802.845215,100.0,1.197455
15639,2024,World,NaN,8.161973e+09,NaN,21653.722656,0.719519,38598.578125,4.729075,43184.085938,4585.508301,15805.253906,12470.595703,8009.827637,100.0,1.216369

In [21]:
world_df = world_df[(world_df["Year"] <= 2022) & (world_df["Year"] >= 1972)]
world_df

,Year,country,iso_code,population,gdp,energy_per_capita,Temperature anomaly,co2,co2_per_capita,co2_including_luc,land_use_change_co2,coal_co2,oil_co2,gas_co2,share_global_co2,temperature_change_from_co2
15587,1972,World,NaN,3.844918e+09,NaN,16308.279297,-0.595112,16224.579102,4.219747,22662.667969,6438.087891,5691.283203,7764.705078,2052.348877,100.000000,0.466356
15588,1973,World,NaN,3.920805e+09,NaN,16919.394531,-0.491711,17077.285156,4.355556,23331.548828,6254.264648,5860.898438,8219.690430,2202.722656,100.000000,0.476618
15589,1974,World,NaN,3.996416e+09,NaN,16689.080078,-0.767671,16997.912109,4.253289,23310.912109,6312.999023,5857.693359,8099.290039,2256.540527,100.000000,0.486888
15590,1975,World,NaN,4.070735e+09,NaN,16497.583984,-0.742727,16988.476562,4.173319,23111.972656,6123.496582,6018.314941,8005.122070,2241.266357,100.000000,0.497088
15591,1976,World,NaN,4.144246e+09,NaN,17070.597656,-0.811458,17862.492188,4.310191,23922.773438,6060.280762,6226.339844,8475.641602,2359.009277,100.000000,0.507656
15592,1977,World,NaN,4.217864e+09,NaN,17379.927734,-0.525560,18358.039062,4.352449,24978.128906,6620.090820,6375.023438,8767.405273,2411.720459,100.000000,0.518694
15593,1978,World,NaN,4.292097e+09,NaN,17748.673828,-0.584493,19024.742188,4.432505,25588.640625,6563.897461,6510.127930,9133.722656,2541.737305,100.000000,0.530005
15594,1979,World,NaN,4.368540e+09,NaN,18014.863281,-0.429016,19508.589844,4.465701,25364.417969,5855.829102,6799.881836,9224.317383,2668.064941,100.000000,0.541213
15595,1980,World,NaN,4.447606e+09,3.198262e+13,17539.898438,-0.297785,19409.792969,4.364099,25411.107422,6001.314453,6984.989746,8912.473633,2741.514160,100.000000,0.552448
15596,1981,World,NaN,4.528777e+09,NaN,17146.964844,-0.264391,18879.755859,4.168842,24716.337891,5836.581055,6942.941406,8483.404297,2763.373047,100.000000,0.563384
15597,1982,World,NaN,4.612673e+09,NaN,16753.320312,-0.463678,18729.742188,4.060496,24261.296875,5531.552734,7066.996582,8276.257812,2701.498535,100.000000,0.574134
15598,1983,World,NaN,4.697328e+09,NaN,16732.732422,-0.268814,18901.775391,4.023942,24741.630859,5839.854004,7269.239258,8214.693359,2743.119629,100.000000,0.585108
15599,1984,World,NaN,4.782176e+09,NaN,17174.082031,-0.481443,19457.250000,4.068702,25882.048828,6424.799316,7586.115234,8238.706055,2972.026855,100.000000,0.596594
15600,1985,World,NaN,4.868943e+09,NaN,17320.572266,-0.521817,20144.863281,4.137420,26932.607422,6787.743164,8144.824219,8247.613281,3089.700195,100.000000,0.608551
15601,1986,World,NaN,4.958073e+09,NaN,17385.945312,-0.433052,20438.044922,4.122175,27381.361328,6943.316406,8261.465820,8490.593750,3014.606445,100.000000,0.620697
15602,1987,World,NaN,5.049746e+09,NaN,17688.300781,-0.277656,21106.189453,4.179654,27604.136719,6497.945312,8549.229492,8579.333008,3281.567139,100.000000,0.632882
15603,1988,World,NaN,5.141993e+09,NaN,18021.527344,-0.245511,21918.755859,4.262697,28075.437500,6156.680176,8836.428711,8889.339844,3435.978027,100.000000,0.645271
15604,1989,World,NaN,5.234432e+09,NaN,18044.753906,-0.363850,22200.212891,4.241189,28181.033203,5980.820312,8827.797852,9037.385742,3604.958496,99.999992,0.657697
15605,1990,World,NaN,5.327803e+09,4.303361e+13,17991.710938,-0.132434,22732.144531,4.266701,28561.214844,5829.069824,8659.787109,9196.439453,3790.181885,100.000000,0.670301
15606,1991,World,NaN,5.418736e+09,NaN,17811.609375,-0.187196,23205.591797,4.282473,28925.888672,5720.297852,8574.089844,9656.487305,3851.520264,99.999992,0.683072
15607,1992,World,NaN,5.505990e+09,NaN,17636.226562,-0.419271,22520.423828,4.090168,28488.322266,5967.898438,8361.173828,9154.655273,3901.366211,100.000000,0.695643
15608,1993,World,NaN,5.591545e+09,NaN,17507.650391,-0.373462,22749.873047,4.068620,28483.164062,5733.292480,8470.028320,9172.321289,4007.804199,100.000008,0.708211
15609,1994,World,NaN,5.675551e+09,NaN,17467.421875,-0.337140,22974.597656,4.047994,29643.505859,6668.907715,8513.747070,9196.235352,4040.173828,100.000000,0.721290
15610,1995,World,NaN,5.758879e+09,NaN,17592.896484,-0.159369,23516.638672,4.083545,29794.718750,6278.080566,8758.441406,9283.901367,4196.847656,100.000000,0.734424
15611,1996,World,NaN,5.842056e+09,NaN,17844.033203,-0.289332,24233.476562,4.148108,30775.304688,6541.827637,8976.963867,9562.136719,4381.598633,100.000008,0.747975
15612,1997,World,NaN,5.924788e+09,NaN,17767.601562,-0.167117,24380.322266,4.114970,32399.937500,8019.616699,8927.299805,9702.210938,4395.057617,100.000000,0.762243
15613,1998,World,NaN,6.007067e+09,NaN,17621.312500,0.021512,24295.712891,4.044522,31087.949219,6792.237793,8689.000977,9821.974609,4443.504395,100.000000,0.775902
15614,1999,World,NaN,6.089006e+09,NaN,17673.488281,-0.247355,24837.771484,4.079117,31399.628906,6561.857422,8809.092773,10064.187500,4586.165527,100.000000,0.789690
15615,2000,World,NaN,6.171703e+09,5.989767e+13,17890.750000,-0.252425,25511.482422,4.133621,31657.244141,6145.761719,9156.637695,10211.624023,4727.822754,100.000008,0.803587
15616,2001,World,NaN,6.254936e+09,NaN,17824.847656,-0.092416,25692.994141,4.107635,31153.697266,5460.703613,9208.428711,10283.570312,4771.714844,100.000000,0.817255
15617,2002,World,NaN,6.337730e+09,NaN,17970.853516,0.004266,26265.332031,4.144280,32359.027344,6093.695801,9630.181641,10269.352539,4913.651855,100.000000,0.831458
15618,2003,World,NaN,6.420362e+09,NaN,18355.601562,-0.008699,27652.691406,4.307030,34973.902344,7321.209473,10466.565430,10540.849609,5096.195801,100.000000,0.846823
15619,2004,World,NaN,6.503378e+09,NaN,19042.679688,-0.070052,28610.023438,4.399256,35053.886719,6443.864746,10813.391602,10924.574219,5257.670410,100.000000,0.862190
15620,2005,World,NaN,6.586970e+09,NaN,19422.695312,0.092185,29598.951172,4.493561,35530.062500,5931.111816,11498.500000,11030.304688,5376.288574,100.000000,0.877756
15621,2006,World,NaN,6.671452e+09,NaN,19708.033203,0.044091,30594.152344,4.585831,36627.894531,6033.740723,12136.238281,11142.927734,5531.005859,100.000000,0.893794
15622,2007,World,NaN,6.757309e+09,NaN,20069.822266,0.036684,31499.255859,4.661509,37092.460938,5593.206055,12724.451172,11184.312500,5736.636719,99.999992,0.910012
15623,2008,World,NaN,6.844458e+09,NaN,20049.712891,-0.095789,32049.660156,4.682571,38000.679688,5951.020020,13149.668945,11143.339844,5905.500488,100.000000,0.926632
15624,2009,World,NaN,6.932766e+09,NaN,19477.537109,0.034867,31513.013672,4.545518,38047.828125,6534.817383,13003.171875,10899.596680,5765.684082,100.000000,0.943296
15625,2010,World,NaN,7.021732e+09,8.980771e+13,20166.255859,0.130550,33317.671875,4.744936,39835.500000,6517.828613,13918.223633,11253.694336,6205.779785,100.000000,0.960736
15626,2011,World,NaN,7.110924e+09,NaN,20378.968750,-0.011309,34479.988281,4.848876,40872.546875,6392.556152,14704.222656,11310.148438,6389.330078,100.000000,0.978629
15627,2012,World,NaN,7.201202e+09,NaN,20413.593750,0.039828,34954.734375,4.854014,41636.855469,6682.122070,14867.801758,11432.715820,6523.143066,100.000000,0.996868
15628,2013,World,NaN,7.291794e+09,NaN,20516.177734,0.067050,35275.820312,4.837743,41595.343750,6319.520996,14953.153320,11516.625977,6573.115723,100.000000,1.015092
15629,2014,World,NaN,7.381616e+09,NaN,20488.625000,0.106208,35465.695312,4.804597,41875.609375,6409.911133,15014.882812,11561.832031,6604.975586,100.000000,1.033443
15630,2015,World,NaN,7.470492e+09,1.068718e+14,20394.589844,0.255577,35403.527344,4.739116,41916.152344,6512.625488,14655.016602,11770.022461,6728.989258,100.000000,1.051799
15631,2016,World,NaN,7.558555e+09,1.104072e+14,20403.568359,0.439195,35392.832031,4.682487,40769.382812,5376.553223,14322.989258,11900.263672,6914.850098,100.000000,1.069632
15632,2017,World,NaN,7.645618e+09,1.145296e+14,20616.425781,0.343641,35974.609375,4.705259,41282.378906,5307.767578,14494.167969,12085.291992,7084.614746,100.000000,1.087686
15633,2018,World,NaN,7.729903e+09,1.187658e+14,20932.492188,0.263885,36734.003906,4.752195,41616.027344,4882.023438,14762.694336,12142.828125,7419.413086,100.000000,1.105875
15634,2019,World,NaN,7.811294e+09,1.221494e+14,20956.146484,0.399228,37086.566406,4.747814,41973.746094,4887.177734,14702.956055,12325.908203,7574.056152,100.000000,1.124223
15635,2020,World,NaN,7.887001e+09,1.185900e+14,20032.187500,0.432163,35158.230469,4.457744,39674.769531,4516.539551,14267.035156,10932.341797,7520.819824,100.000000,1.141716
15636,2021,World,NaN,7.954448e+09,1.260048e+14,20874.294922,0.273691,36866.863281,4.634748,41523.964844,4657.103027,14969.249023,11513.166016,7878.698242,100.000000,1.160024
15637,2022,World,NaN,8.021407e+09,1.301126e+14,21076.292969,0.300865,37527.773438,4.678452,42313.164062,4785.391602,15449.176758,11914.912109,7758.745605,100.000000,1.178648

In [22]:
# Getting rid of any rows containing an NA
df = df.dropna()
df.shape

(4448, 16)

Creating a list of countries with the correct country name added for use of ISO codes

In [23]:
# Manual lookup for countries that dont have correct ISO name
country_corrections = {
    "Cote d'Ivoire": "Côte d'Ivoire",
    "Democratic Republic of Congo": "Congo, The Democratic Republic of the",
    "Congo": "Congo",
    "Tanzania": "Tanzania, United Republic of",
    "South Korea": "Korea, Republic of",
    "North Korea": "Korea, Democratic People's Republic of",
    "Laos": "Lao People's Democratic Republic",
    "Syria": "Syrian Arab Republic",
    "Russia": "Russian Federation",
    "Vietnam": "Viet Nam",
    "Bolivia": "Bolivia, Plurinational State of",
    "Moldova": "Moldova, Republic of",
    "Venezuela": "Venezuela, Bolivarian Republic of",
    "Iran": "Iran, Islamic Republic of",
    "Palestine": "Palestine, State of",
    "Brunei": "Brunei Darussalam",
    "Cape Verde": "Cabo Verde",
    "Swaziland": "Eswatini",
    "Turkey": "Türkiye"
}

In [24]:
# removing world
country_df = df[df['country'] != "World"]
country_df

,Year,country,iso_code,population,gdp,energy_per_capita,Temperature anomaly,co2,co2_per_capita,co2_including_luc,land_use_change_co2,coal_co2,oil_co2,gas_co2,share_global_co2,temperature_change_from_co2
40,1980,Afghanistan,AFG,13169313.0,1.532984e+10,481.208618,-0.059716,1.756302,0.133363,4.339825,2.583523,0.315762,0.925256,0.187254,0.009049,0.000467
41,1981,Afghanistan,AFG,11937586.0,1.564534e+10,610.638977,-0.327458,1.978463,0.165734,4.677109,2.698646,0.333424,1.014928,0.304112,0.010479,0.000470
42,1982,Afghanistan,AFG,10991380.0,1.598041e+10,717.766418,-1.718081,2.094581,0.190566,4.267553,2.172972,0.384720,0.992944,0.395712,0.011183,0.000472
43,1983,Afghanistan,AFG,10917985.0,1.675533e+10,905.126648,-0.780836,2.519954,0.230808,4.644854,2.124900,0.384720,1.220112,0.615552,0.013332,0.000475
44,1984,Afghanistan,AFG,11190222.0,1.707215e+10,887.370972,-0.886393,2.821540,0.252143,4.676733,1.855193,0.392556,1.133644,0.931863,0.014501,0.000478
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15718,2018,Yemen,YEM,34085181.0,6.527121e+10,1109.117920,-0.031227,11.503876,0.337504,11.394616,-0.109260,0.271136,9.504416,0.040304,0.031317,0.000283
15719,2019,Yemen,YEM,35111416.0,6.618501e+10,1085.563599,0.521249,11.787783,0.335725,11.630597,-0.157186,0.278378,9.358638,0.040292,0.031785,0.000288
15720,2020,Yemen,YEM,36134867.0,6.055929e+10,918.665466,0.108743,10.757014,0.297691,10.621593,-0.135421,0.252816,8.137744,0.040304,0.030596,0.000293
15721,2021,Yemen,YEM,37140234.0,5.995369e+10,863.311096,0.068503,10.607956,0.285619,10.543360,-0.064596,0.252730,7.819967,0.040290,0.028774,0.000298
15722,2022,Yemen,YEM,38222878.0,6.085300e+10,893.954773,0.116327,10.403769,0.272187,10.425753,0.021984,0.256391,7.951772,0.040290,0.027723,0.000302

In [25]:
# adding continent column for continental analysis

def continent_name(country_name):
  # correcting names for usable ISO name
  country_name = country_corrections.get(country_name, country_name)

  # lookup name and find matching continent code and name
  country = pc.countries.lookup(country_name)
  alpha2 = country.alpha_2
  continent_code = pcc.country_alpha2_to_continent_code(alpha2)
  continent_name = pcc.convert_continent_code_to_continent_name(continent_code)

  return continent_name

# Applying function to add continent name
country_df['Continent'] = country_df['country'].apply(continent_name)
country_df

,Year,country,iso_code,population,gdp,energy_per_capita,Temperature anomaly,co2,co2_per_capita,co2_including_luc,land_use_change_co2,coal_co2,oil_co2,gas_co2,share_global_co2,temperature_change_from_co2,Continent
40,1980,Afghanistan,AFG,13169313.0,1.532984e+10,481.208618,-0.059716,1.756302,0.133363,4.339825,2.583523,0.315762,0.925256,0.187254,0.009049,0.000467,Asia
41,1981,Afghanistan,AFG,11937586.0,1.564534e+10,610.638977,-0.327458,1.978463,0.165734,4.677109,2.698646,0.333424,1.014928,0.304112,0.010479,0.000470,Asia
42,1982,Afghanistan,AFG,10991380.0,1.598041e+10,717.766418,-1.718081,2.094581,0.190566,4.267553,2.172972,0.384720,0.992944,0.395712,0.011183,0.000472,Asia
43,1983,Afghanistan,AFG,10917985.0,1.675533e+10,905.126648,-0.780836,2.519954,0.230808,4.644854,2.124900,0.384720,1.220112,0.615552,0.013332,0.000475,Asia
44,1984,Afghanistan,AFG,11190222.0,1.707215e+10,887.370972,-0.886393,2.821540,0.252143,4.676733,1.855193,0.392556,1.133644,0.931863,0.014501,0.000478,Asia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15718,2018,Yemen,YEM,34085181.0,6.527121e+10,1109.117920,-0.031227,11.503876,0.337504,11.394616,-0.109260,0.271136,9.504416,0.040304,0.031317,0.000283,Asia
15719,2019,Yemen,YEM,35111416.0,6.618501e+10,1085.563599,0.521249,11.787783,0.335725,11.630597,-0.157186,0.278378,9.358638,0.040292,0.031785,0.000288,Asia
15720,2020,Yemen,YEM,36134867.0,6.055929e+10,918.665466,0.108743,10.757014,0.297691,10.621593,-0.135421,0.252816,8.137744,0.040304,0.030596,0.000293,Asia
15721,2021,Yemen,YEM,37140234.0,5.995369e+10,863.311096,0.068503,10.607956,0.285619,10.543360,-0.064596,0.252730,7.819967,0.040290,0.028774,0.000298,Asia
15722,2022,Yemen,YEM,38222878.0,6.085300e+10,893.954773,0.116327,10.403769,0.272187,10.425753,0.021984,0.256391,7.951772,0.040290,0.027723,0.000302,Asia

In [ ]:
country_df = country_df[(country_df["Year"] <= 2022) & (country_df["Year"] >= 1972)]

,Year,country,iso_code,population,gdp,energy_per_capita,Temperature anomaly,co2,co2_per_capita,co2_including_luc,land_use_change_co2,coal_co2,oil_co2,gas_co2,share_global_co2,temperature_change_from_co2,Continent
40,1980,Afghanistan,AFG,13169313.0,1.532984e+10,481.208618,-0.059716,1.756302,0.133363,4.339825,2.583523,0.315762,0.925256,0.187254,0.009049,0.000467,Asia
41,1981,Afghanistan,AFG,11937586.0,1.564534e+10,610.638977,-0.327458,1.978463,0.165734,4.677109,2.698646,0.333424,1.014928,0.304112,0.010479,0.000470,Asia
42,1982,Afghanistan,AFG,10991380.0,1.598041e+10,717.766418,-1.718081,2.094581,0.190566,4.267553,2.172972,0.384720,0.992944,0.395712,0.011183,0.000472,Asia
43,1983,Afghanistan,AFG,10917985.0,1.675533e+10,905.126648,-0.780836,2.519954,0.230808,4.644854,2.124900,0.384720,1.220112,0.615552,0.013332,0.000475,Asia
44,1984,Afghanistan,AFG,11190222.0,1.707215e+10,887.370972,-0.886393,2.821540,0.252143,4.676733,1.855193,0.392556,1.133644,0.931863,0.014501,0.000478,Asia
45,1985,Afghanistan,AFG,11426855.0,1.710848e+10,842.730957,-0.298625,3.501422,0.306420,5.075586,1.574164,0.399794,1.547825,1.192046,0.017381,0.000481,Asia
46,1986,Afghanistan,AFG,11420074.0,1.764134e+10,875.000305,-1.225358,3.133645,0.274398,4.406152,1.272507,0.425024,1.139504,1.201792,0.015332,0.000484,Asia
47,1987,Afghanistan,AFG,11387822.0,1.581082e+10,1486.686646,0.099336,3.113826,0.273435,4.137804,1.023978,0.442824,2.012838,0.391588,0.014753,0.000486,Asia
48,1988,Afghanistan,AFG,11523299.0,1.449907e+10,2697.882080,0.384678,2.856896,0.247923,3.866218,1.009322,0.366400,1.821008,0.439680,0.013034,0.000489,Asia
49,1989,Afghanistan,AFG,11874089.0,1.348950e+10,2569.341797,-1.639677,2.764855,0.232848,3.688476,0.923621,0.337088,1.864976,0.479984,0.012454,0.000491,Asia

In [31]:
world_df.to_csv("../Data/world_data.csv", index=False)
country_df.to_csv("../Data/country_data.csv", index=False)